# Generated by Django 2.1.1 on 2018-12-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='G',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.UserGroup'),
        ),
    ]
