# Generated by Django 2.1.1 on 2018-12-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181219_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='department',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='position',
            field=models.CharField(max_length=256),
        ),
    ]
