# Generated by Django 2.1.1 on 2018-12-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181219_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
