# Generated by Django 2.1.1 on 2018-12-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181224_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='position_id',
        ),
    ]
